### ISSUE TITLE
When an app crashes, another app unnecessarily opens

### ISSUE THREAD

**Issue by futureshape** [emfcamp/badge-2024-software#112] opened 2024-06-05 17:06 UTC
**Steps to reproduce:**

* Open an up that crashes on startup
* Observe that:
  - the banner "{app name} has crashed" appears on top of the screen 
  - another app has launched in the background (this seems to be the one before or after in the menu)

**Expected behaviour:**
The badge returns to the main menu

**Comment by npentrel** [comment] 2024-08-04 16:02
I can't reproduce this in v1.9.0. Opening a crashing app just triggers the banner.

I will close this for now, if we see it again, we can reopen this or open a new issue.

**Closed by npentrel** 2024-08-04 16:02 UTC
Labels: bug
